### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by hroma** [apphp/directy-cmf#1]
Hi, i've tried to fresh install directy-cmf last release and got the following error:

`Fatal error: Uncaught PDOException: There is no active transaction in \protected\modules\setup\models\Setup.php:89 Stack trace: #0`

and got also:

`Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in \framework\helpers\CFilter.php on line 38`

**Comment by apphp** [comment]
Fixed, please re-check
